### ISSUE TITLE
Changing target names - have to edit .chaletrc file

### ISSUE THREAD

**Issue by dimitre** [chalet-org/chalet#245]
After changing target names Chalet keep asking for the previous project name, unless you go and edit .chaletrc file manually
is there some way of updating this by the chalet command itself?

**Comment by rewrking** [comment]
Btw, the only reason I don't do this automatically is because it would be more confusing. If it's a project with multiple executables, and the "current" project was renamed, the app would have to guess which ones (first executable target). It did do that a while ago (more than a year ago probably), but I took it out because it feelt too automatic and might lead to someone going "wait, why did this target just launch?"
