### ISSUE TITLE
custom toolchain with a custom compiler

### ISSUE THREAD

**Issue by dimitre** [chalet-org/chalet#247]
is there some way of creating a preset with a custom compiler? I'm interested in using "include-what-you-use" clang fork, or zapcc in chalet.
I've tried to add new entries in .chaletrc file but It seems I'm doing it wrong
```
ERROR: The toolchain 'iwyu' (arch: arm64) could either not be detected or was not defined in settings.
```
Thanks

**Comment by rewrking** [comment]
If it's a clang variant, you should be able to - although maybe not on macos. Keep in mind apple-llvm is Apple's own fork (from Xcode/Command Line Tools) and has a ton of apple-specific stuff in it.

Start in a blank directory and create a new project with `chalet init`. Add a .env when it asks. Say N when it asks to configure the project at the end.

In the .env, add:

```env
PATH=/path/to/iwyu:$PATH
```

Then try `chalet configure -t llvm -a auto` (or llvm-(suffix) if the bin directory contains a clang executable with a suffix). If that succeeded, try running `build`. You should have a toolchain in .chaletrc with the one in path if it was detected correctly. You can then rename that toolchain and copy it to `~/.chalet/config.json` if you want to use it in other projects. Also, you can append `--save-user-toolchain-globally` to a command to do it for you during the next build.

**Comment by dimitre** [comment]
Thanks about the instructions, maybe I have to spend some more time on it in the future
I've added llvm to path but it is not working yet here
and ```chalet configure -t llvm -a auto``` command throws an error ```ERROR: Uncaught exception: unordered_map::at: key not found```

So I won't be using it right now. I can already switch back and forth using Make, and it is a compiler to use only once to analyse optional includes. 
Feel free to close this issue.

**Comment by rewrking** [comment]
I added some changes for this in `main` if you want to try them out. At the moment, the below `.env` treats a custom toolchain as LLVM or GCC depending on if `__clang__` or  `__GNUC__` (or mingw flavors) is defined by the compiler.

This really only affects the initial toolchain detection, so on repeated commands, the one in settings will be preferred. In order to make this work, set the cli `--toolchain` to the same name as `CHALET_TOOLCHAIN_NAME`. Any other toolchain name or preset will ignore the rest of the `CHALET_TOOLCHAIN_*` environment variables.

Blank or undefined `CHALET_TOOLCHAIN_*` variables will try to guess the tool based on LLVM and GCC tool names if they are found in Path.

Here's a windows .env example (macOS would use PATH, colons and backslashes as you would expect):
```env
Path=%HOME%\compilers\zapcc\bin;C:\msys64\mingw64\bin;%Path%
CHALET_TOOLCHAIN_NAME=zapcc
CHALET_TOOLCHAIN_COMPILER_CPP=zapcc++
CHALET_TOOLCHAIN_COMPILER_C=zapcc
CHALET_TOOLCHAIN_COMPILER_RC=
CHALET_TOOLCHAIN_LINKER=
CHALET_TOOLCHAIN_ARCHIVER=
CHALET_TOOLCHAIN_PROFILER=
CHALET_TOOLCHAIN_DISASSEMBLER=
```

In the above, `Path` is allowing that if the tool is not in `%HOME%\compilers\zapcc\bin`, it may be found in `C:\msys64\mingw64\bin`. 

A neat side effect of this is that if you are building with a bunch of custom toolchains, you can write a .env for each one and select them with `-e (envFile) -t (name)`.

To be honest though, I could get a basic program to compile with zapcc, but it would not run. I'm not sure if the compiler was compiled incorrectly -- the mingw version might be too new or something.
